import { createContext, useContext, useState, useEffect, useMemo } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', voiceLang: 'en-IN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', voiceLang: 'hi-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🚩', voiceLang: 'mr-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳', voiceLang: 'bn-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', voiceLang: 'ta-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', voiceLang: 'te-IN' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳', voiceLang: 'gu-IN' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳', voiceLang: 'kn-IN' },
];

export const TRANSLATIONS = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.airQualityMap': 'Air Quality Map',
    'nav.aiAssistant': 'AI Assistant',
    'nav.diseases': 'Diseases',
    'nav.surveillance': 'Surveillance',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.systemActive': 'System Status: Active',

    // Topbar
    'topbar.searchPlaceholder': 'Search locations, diseases or health topics...',
    'topbar.notifications': 'Notifications',
    'topbar.markAllRead': 'Mark all read',
    'topbar.dismissAll': 'Dismiss all',
    'topbar.noNotifications': 'No notifications',
    'topbar.allCaughtUp': 'All caught up!',
    'topbar.selectLanguage': 'Language',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Here is your daily environmental health overview.',
    'dashboard.searchCity': 'Enter a city',
    'dashboard.useMyLocation': 'Use my location',
    'dashboard.locating': 'Locating...',
    'dashboard.currentAqi': 'Current Air Quality',
    'dashboard.environmentalImpact': 'Environmental Impact',
    'dashboard.hoursAvoided': 'hours of unhealthy air exposure avoided this week.',
    'dashboard.impactNote': 'By adjusting route recommendations during peak pollution hours.',
    'dashboard.livePollutants': 'Live Pollutants',
    'dashboard.historicalTrend': 'Historical AQI Trend',
    'dashboard.aiInsights': 'AI Health Insights',
    'dashboard.viewReport': 'View Detailed Report',
    'dashboard.primaryPollutant': 'Primary Pollutant',
    'dashboard.lastUpdated': 'Last updated',

    // Precautions & Disease Risks
    'precautions.title': 'Daily Personalized Precautions',
    'precautions.subtitle': 'Tailored preventive measures for your health profile & today\'s air quality',
    'precautions.outdoor': 'Outdoor Activity Guidance',
    'precautions.protection': 'Protection & Mask Guidance',
    'precautions.indoor': 'Indoor Air & Ventilation',
    'precautions.ayurvedic': 'Ayurvedic & Home Remedies',
    'precautions.hydration': 'Hydration & Nutrition',
    'precautions.sensitiveAlert': 'Health Alert for Your Profile',

    'risks.title': 'Likely Conditions & Environmental Risk Radar',
    'risks.subtitle': 'Conditions triggered or exacerbated by current pollutants and weather',
    'risks.riskScore': 'Risk Score',
    'risks.triggers': 'Main Triggers',
    'risks.watchVideo': 'Watch Impact Video',
    'risks.viewDetails': 'View Disease Details',

    // AQI Status
    'aqi.good': 'Good',
    'aqi.moderate': 'Moderate',
    'aqi.poor': 'Poor',
    'aqi.unhealthySensitive': 'Unhealthy for Sensitive Groups',
    'aqi.unhealthy': 'Unhealthy',
    'aqi.veryUnhealthy': 'Very Unhealthy',
    'aqi.hazardous': 'Hazardous',

    // Video Modal
    'video.title': 'Future Deep Impact Video Analysis',
    'video.play': 'Play Video',
    'video.pause': 'Pause Video',
    'video.listenAudio': 'Listen Audio',
    'video.stopAudio': 'Stop Audio',
    'video.narration': 'Clinical Audio Narration',
    'video.progressionTimeline': 'Future Disease Progression Timeline',
    'video.selectStage': 'Select Stage to View Impact',
    'video.organImpairment': 'Organ Impairment & Pathology Metrics',
    'video.airwayOcclusion': 'Airway / Tissue Occlusion',
    'video.parenchymalFibrosis': 'Parenchymal Fibrosis',
    'video.systemicStrain': 'Organ Workload & Systemic Strain',
    'video.howToHalt': 'How to Halt & Reverse Future Progression',
    'video.language': 'Narration Language',

    // Common
    'common.go': 'Go',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.low': 'Low',
  },

  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.airQualityMap': 'वायु गुणवत्ता मानचित्र',
    'nav.aiAssistant': 'एआई सहायक',
    'nav.diseases': 'रोग व बीमारियाँ',
    'nav.surveillance': 'स्वास्थ्य निगरानी',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉग आउट',
    'nav.systemActive': 'सिस्टम स्थिति: सक्रिय',

    'topbar.searchPlaceholder': 'स्थान, बीमारी या स्वास्थ्य विषय खोजें...',
    'topbar.notifications': 'सूचनाएं',
    'topbar.markAllRead': 'सभी पढ़ा हुआ चिह्नित करें',
    'topbar.dismissAll': 'सभी हटाएं',
    'topbar.noNotifications': 'कोई नई सूचना नहीं है',
    'topbar.allCaughtUp': 'सब कुछ अद्यतित है!',
    'topbar.selectLanguage': 'भाषा',

    'dashboard.welcome': 'पुनः स्वागत है',
    'dashboard.subtitle': 'यहाँ आपका दैनिक पर्यावरणीय स्वास्थ्य अवलोकन है।',
    'dashboard.searchCity': 'शहर का नाम दर्ज करें',
    'dashboard.useMyLocation': 'मेरा वर्तमान स्थान उपयोग करें',
    'dashboard.locating': 'स्थान खोजा जा रहा है...',
    'dashboard.currentAqi': 'वर्तमान वायु गुणवत्ता (AQI)',
    'dashboard.environmentalImpact': 'पर्यावरणीय प्रभाव',
    'dashboard.hoursAvoided': 'घंटे अस्वस्थ हवा के संपर्क से इस सप्ताह बचे।',
    'dashboard.impactNote': 'प्रदूषण के चरम समय में सुरक्षित मार्ग सिफारिशों द्वारा।',
    'dashboard.livePollutants': 'सक्रिय प्रदूषक',
    'dashboard.historicalTrend': 'ऐतिहासिक AQI रुझान',
    'dashboard.aiInsights': 'एआई स्वास्थ्य अंतर्दृष्टि',
    'dashboard.viewReport': 'विस्तृत रिपोर्ट देखें',
    'dashboard.primaryPollutant': 'मुख्य प्रदूषक',
    'dashboard.lastUpdated': 'अंतिम अपडेट',

    'precautions.title': 'दैनिक व्यक्तिगत सावधानियां',
    'precautions.subtitle': 'आपकी स्वास्थ्य प्रोफ़ाइल और आज की वायु गुणवत्ता के आधार पर निवारक उपाय',
    'precautions.outdoor': 'बाहरी गतिविधि दिशानिर्देश',
    'precautions.protection': 'सुरक्षा व मास्क संबंधी सलाह',
    'precautions.indoor': 'घर के अंदर की वायु व वेंटिलेशन',
    'precautions.ayurvedic': 'आयुर्वेदिक व घरेलू उपचार',
    'precautions.hydration': 'जलयोजन व पोषण',
    'precautions.sensitiveAlert': 'आपकी प्रोफ़ाइल के लिए स्वास्थ्य चेतावनी',

    'risks.title': 'संभावित रोग व पर्यावरणीय जोखिम रडार',
    'risks.subtitle': 'वर्तमान प्रदूषकों और मौसम की स्थिति से बढ़ने वाले संभावित रोग',
    'risks.riskScore': 'जोखिम स्कोर',
    'risks.triggers': 'मुख्य कारण/ट्रिगर',
    'risks.watchVideo': 'प्रभाव वीडियो देखें',
    'risks.viewDetails': 'रोग विवरण देखें',

    'aqi.good': 'अच्छा (Good)',
    'aqi.moderate': 'मध्यम (Moderate)',
    'aqi.poor': 'खराब (Poor)',
    'aqi.unhealthySensitive': 'संवेदनशील समूहों के लिए अस्वास्थ्यकर',
    'aqi.unhealthy': 'अस्वास्थ्यकर (Unhealthy)',
    'aqi.veryUnhealthy': 'बहुत अस्वास्थ्यकर (Very Unhealthy)',
    'aqi.hazardous': 'अत्यंत खतरनाक (Hazardous)',

    'video.title': 'भविष्य के गहरे प्रभाव का वीडियो विश्लेषण',
    'video.play': 'वीडियो चलाएं',
    'video.pause': 'रोकें',
    'video.listenAudio': 'ऑडियो सुनें',
    'video.stopAudio': 'ऑडियो बंद करें',
    'video.narration': 'चिकित्सीय ऑडियो विवरण',
    'video.progressionTimeline': 'भविष्य रोग प्रगति समयरेखा',
    'video.selectStage': 'प्रभाव देखने हेतु चरण चुनें',
    'video.organImpairment': 'अंग क्षति व पैथोलॉजी मेट्रिक्स',
    'video.airwayOcclusion': 'वायुमार्ग रुकावट',
    'video.parenchymalFibrosis': 'पैरेन्काइमल फाइब्रोसिस',
    'video.systemicStrain': 'अंग कार्यभार व दैहिक तनाव',
    'video.howToHalt': 'भविष्य के प्रभाव को कैसे रोकें व सुधारें',
    'video.language': 'विवरण भाषा',

    'common.go': 'खोजें',
    'common.refresh': 'ताज़ा करें',
    'common.loading': 'लोड हो रहा है...',
    'common.close': 'बंद करें',
    'common.open': 'खोलें',
    'common.critical': 'गंभीर',
    'common.high': 'उच्च',
    'common.low': 'कम',
  },

  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.airQualityMap': 'हवा गुणवत्ता नकाशा',
    'nav.aiAssistant': 'एआय सहाय्यक',
    'nav.diseases': 'आजारी व रोग',
    'nav.surveillance': 'आरोग्य देखरेख',
    'nav.profile': 'माझे प्रोफाइल',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'बाहेर पडा',
    'nav.systemActive': 'प्रणाली स्थिती: सक्रिय',

    'topbar.searchPlaceholder': 'ठिकाण, रोग किंवा आरोग्य विषय शोधा...',
    'topbar.notifications': 'सूचना',
    'topbar.markAllRead': 'सर्व वाचलेले म्हणून चिन्हांकित करा',
    'topbar.dismissAll': 'सर्व काढा',
    'topbar.noNotifications': 'कोणत्याही नवीन सूचना नाहीत',
    'topbar.allCaughtUp': 'सर्व अद्ययावत आहे!',
    'topbar.selectLanguage': 'भाषा',

    'dashboard.welcome': 'पुन्हा स्वागत आहे',
    'dashboard.subtitle': 'येथे तुमचे दैनिक पर्यावरणीय आरोग्य अवलोकन आहे.',
    'dashboard.searchCity': 'शहराचे नाव टाका',
    'dashboard.useMyLocation': 'माझे स्थान वापरा',
    'dashboard.locating': 'स्थान शोधत आहे...',
    'dashboard.currentAqi': 'सध्याची हवा गुणवत्ता (AQI)',
    'dashboard.environmentalImpact': 'पर्यावरणीय प्रभाव',
    'dashboard.hoursAvoided': 'तास या आठवड्यात अस्वच्छ हवेपासून बचाव झाला.',
    'dashboard.impactNote': 'प्रदूषणाच्या वेळी सुरक्षित मार्गांचा वापर केल्यामुळे.',
    'dashboard.livePollutants': 'सक्रिय प्रदूषक',
    'dashboard.historicalTrend': 'ऐतिहासिक AQI कल',
    'dashboard.aiInsights': 'एआय आरोग्य माहिती',
    'dashboard.viewReport': 'सविस्तर अहवाल पहा',
    'dashboard.primaryPollutant': 'मुख्य प्रदूषक',
    'dashboard.lastUpdated': 'शेवटचे अद्यतन',

    'precautions.title': 'दैनिक वैयक्तिक खबरदारी',
    'precautions.subtitle': 'तुमच्या आरोग्यानुसार आणि आजच्या हवेच्या गुणवत्तेनुसार प्रतिबंधक उपाय',
    'precautions.outdoor': 'बाहेरील हालचाली मार्गदर्शक',
    'precautions.protection': 'संरक्षण व मास्क सल्ला',
    'precautions.indoor': 'घरातील हवा व वेंटिलेशन',
    'precautions.ayurvedic': 'आयुर्वेदिक व घरगुती उपाय',
    'precautions.hydration': 'पाणी पिणे व पोषण',
    'precautions.sensitiveAlert': 'तुमच्या आरोग्यासाठी खबरदारीची सूचना',

    'risks.title': 'संभाव्य आजार व पर्यावरणीय धोका रडार',
    'risks.subtitle': 'सध्याच्या प्रदूषणामुळे आणि हवामानामुळे उद्भवू शकणारे आजार',
    'risks.riskScore': 'धोका प्रमाण',
    'risks.triggers': 'मुख्य कारणे',
    'risks.watchVideo': 'प्रभाव व्हिडिओ पहा',
    'risks.viewDetails': 'आजार माहिती पहा',

    'aqi.good': 'उत्तम (Good)',
    'aqi.moderate': 'मध्यम (Moderate)',
    'aqi.poor': 'खराब (Poor)',
    'aqi.unhealthySensitive': 'संवेदनशील व्यक्तींसाठी अस्वस्थ',
    'aqi.unhealthy': 'अस्वस्थ (Unhealthy)',
    'aqi.veryUnhealthy': 'खूप अस्वस्थ (Very Unhealthy)',
    'aqi.hazardous': 'धोकादायक (Hazardous)',

    'video.title': 'भविष्यातील सखोल प्रभावाचे व्हिडिओ विश्लेषण',
    'video.play': 'व्हिडिओ सुरू करा',
    'video.pause': 'थांबवा',
    'video.listenAudio': 'ऑडिओ ऐका',
    'video.stopAudio': 'ऑडिओ बंद करा',
    'video.narration': 'वैद्यकीय ऑडिओ वर्णन',
    'video.progressionTimeline': 'भविष्यातील रोग प्रगती कालरेषा',
    'video.selectStage': 'प्रभाव पाहण्यासाठी टप्पा निवडा',
    'video.organImpairment': 'अवयव नुकसान व पॅथॉलॉजी मेट्रिक्स',
    'video.airwayOcclusion': 'श्वसनमार्ग अडथळा',
    'video.parenchymalFibrosis': 'फायब्रोसिस प्रमाण',
    'video.systemicStrain': 'हृदय व अवयव ताण',
    'video.howToHalt': 'भविष्यातील आजार कसे रोखावे',
    'video.language': 'वर्णन भाषा',

    'common.go': 'शोधा',
    'common.refresh': 'ताजे करा',
    'common.loading': 'लोड होत आहे...',
    'common.close': 'बंद करा',
    'common.open': 'उघडा',
    'common.critical': 'गंभीर',
    'common.high': 'जास्त',
    'common.low': 'कमी',
  },

  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.airQualityMap': 'বায়ু গুণমান মানচিত্র',
    'nav.aiAssistant': 'এআই সহকারী',
    'nav.diseases': 'রোগ ও স্বাস্থ্য',
    'nav.surveillance': 'স্বাস্থ্য নজরদারি',
    'nav.profile': 'প্রোফাইল',
    'nav.settings': 'সেটিংস',
    'nav.logout': 'লগ আউট',
    'nav.systemActive': 'সিস্টেম স্ট্যাটাস: সক্রিয়',

    'topbar.searchPlaceholder': 'স্থান, রোগ বা স্বাস্থ্য সংক্রান্ত বিষয় খুঁজুন...',
    'topbar.notifications': 'বিজ্ঞপ্তি',
    'topbar.markAllRead': 'সব পঠিত চিহ্নিত করুন',
    'topbar.dismissAll': 'সব খারিজ করুন',
    'topbar.noNotifications': 'কোন নতুন বিজ্ঞপ্তি নেই',
    'topbar.allCaughtUp': 'সব আপডেট করা আছে!',
    'topbar.selectLanguage': 'ভাষা',

    'dashboard.welcome': 'স্বাগতম',
    'dashboard.subtitle': 'এখানে আপনার দৈনিক পরিবেশগত স্বাস্থ্য বিবরণী রয়েছে।',
    'dashboard.searchCity': 'শহরের নাম লিখুন',
    'dashboard.useMyLocation': 'আমার বর্তমান অবস্থান ব্যবহার করুন',
    'dashboard.locating': 'অবস্থান খোঁজা হচ্ছে...',
    'dashboard.currentAqi': 'বর্তমান বায়ু গুণমান (AQI)',
    'dashboard.environmentalImpact': 'পরিবেশগত প্রভাব',
    'dashboard.hoursAvoided': 'ঘন্টা দূষিত বায়ু থেকে রেহাই পাওয়া গেছে এই সপ্তাহে।',
    'dashboard.impactNote': 'দূষণের পিক সময়ে নিরাপদ রুট অবলম্বনের মাধ্যমে।',
    'dashboard.livePollutants': 'সক্রিয় দূষকসমূহ',
    'dashboard.historicalTrend': 'ঐতিহাসিক AQI ট্রেন্ড',
    'dashboard.aiInsights': 'এআই স্বাস্থ্য অন্তর্দৃষ্টি',
    'dashboard.viewReport': 'বিস্তারিত রিপোর্ট দেখুন',
    'dashboard.primaryPollutant': 'প্রধান দূষক',
    'dashboard.lastUpdated': 'সর্বশেষ আপডেট',

    'precautions.title': 'দৈনিক ব্যক্তিগত সতর্কতা',
    'precautions.subtitle': 'আপনার স্বাস্থ্য প্রোফাইল এবং আজকের বায়ু মানের উপর ভিত্তি করে প্রতিরোধমূলক ব্যবস্থা',
    'precautions.outdoor': 'বাইরে যাওয়ার পরামর্শ',
    'precautions.protection': 'সুরক্ষা ও মাস্ক ব্যবহার',
    'precautions.indoor': 'ঘরের বাতাস ও বায়ু চলাচল',
    'precautions.ayurvedic': 'আয়ুর্বেদিক ও ঘরোয়া প্রতিকার',
    'precautions.hydration': 'জলপান ও পুষ্টি',
    'precautions.sensitiveAlert': 'আপনার স্বাস্থ্যের জন্য বিশেষ সতর্কতা',

    'risks.title': 'সম্ভাব্য রোগ ও পরিবেশগত ঝুঁকি রাডার',
    'risks.subtitle': 'বর্তমান দূষণ ও আবহাওয়ার কারণে সম্ভাব্য স্বাস্থ্য সমস্যা',
    'risks.riskScore': 'ঝুঁকি স্কোর',
    'risks.triggers': 'প্রধান কারণ',
    'risks.watchVideo': 'প্রভাব ভিডিও দেখুন',
    'risks.viewDetails': 'রোগের বিবরণ দেখুন',

    'aqi.good': 'ভালো (Good)',
    'aqi.moderate': 'মাঝারি (Moderate)',
    'aqi.poor': 'খারাপ (Poor)',
    'aqi.unhealthySensitive': 'সংবেদনশীলদের জন্য অস্বাস্থ্যকর',
    'aqi.unhealthy': 'অস্বাস্থ্যকর (Unhealthy)',
    'aqi.veryUnhealthy': 'খুব অস্বাস্থ্যকর (Very Unhealthy)',
    'aqi.hazardous': 'মারাত্মক ক্ষতিকর (Hazardous)',

    'video.title': 'ভবিষ্যত গভীর প্রভাবের ভিডিও বিশ্লেষণ',
    'video.play': 'ভিডিও চালান',
    'video.pause': 'থামান',
    'video.listenAudio': 'অডিও শুনুন',
    'video.stopAudio': 'অডিও বন্ধ করুন',
    'video.narration': 'ক্লিনিকাল অডিও বর্ণনা',
    'video.progressionTimeline': 'ভবিষ্যত রোগের অগ্রগতির সময়রেখা',
    'video.selectStage': 'প্রভাব দেখতে পর্যায় নির্বাচন করুন',
    'video.organImpairment': 'অঙ্গ ক্ষতি ও প্যাথলজি মেট্রিক্স',
    'video.airwayOcclusion': 'শ্বাসনালী অবরোধ',
    'video.parenchymalFibrosis': 'ফুসফুসের ফাইব্রোসিস',
    'video.systemicStrain': 'অঙ্গ ও শারীরিক চাপ',
    'video.howToHalt': 'রোগের অগ্রগতি কীভাবে রোধ করবেন',
    'video.language': 'বর্ণনার ভাষা',

    'common.go': 'যান',
    'common.refresh': 'রিফ্রেশ',
    'common.loading': 'লোড হচ্ছে...',
    'common.close': 'বন্ধ করুন',
    'common.open': 'খুলুন',
    'common.critical': 'সংকটজনক',
    'common.high': 'উচ্চ',
    'common.low': 'কম',
  },

  ta: {
    'nav.dashboard': 'முகப்புப்பலகை',
    'nav.airQualityMap': 'காற்றுத் தர வரைபடம்',
    'nav.aiAssistant': 'AI உதவியாளர்',
    'nav.diseases': 'நோய்கள்',
    'nav.surveillance': 'சுகாதாரக் கண்காணிப்பு',
    'nav.profile': 'சுயவிவரம்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    'nav.systemActive': 'கணினி நிலை: செயலில் உள்ளது',

    'topbar.searchPlaceholder': 'இடம், நோய் அல்லது தலைப்புகளைத் தேடுங்கள்...',
    'topbar.notifications': 'அறிவிப்புகள்',
    'topbar.markAllRead': 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    'topbar.dismissAll': 'அனைத்தையும் நீக்கு',
    'topbar.noNotifications': 'புதிய அறிவிப்புகள் இல்லை',
    'topbar.allCaughtUp': 'அனைத்தும் புதுப்பிக்கப்பட்டுள்ளது!',
    'topbar.selectLanguage': 'மொழி',

    'dashboard.welcome': 'மீண்டும் வருக',
    'dashboard.subtitle': 'உங்கள் தினசரி சுற்றுச்சூழல் சுகாதார கண்ணோட்டம் இங்கே.',
    'dashboard.searchCity': 'நகரத்தின் பெயரை உள்ளிடவும்',
    'dashboard.useMyLocation': 'எனது இருப்பிடத்தைப் பயன்படுத்து',
    'dashboard.locating': 'இருப்பிடம் தேடப்படுகிறது...',
    'dashboard.currentAqi': 'தற்போதைய காற்று தரம் (AQI)',
    'dashboard.environmentalImpact': 'சுற்றுச்சூழல் தாக்கம்',
    'dashboard.hoursAvoided': 'மணிநேர ஆபத்தான காற்று வெளிப்பாடு இந்த வாரம் தவிர்க்கப்பட்டது.',
    'dashboard.impactNote': 'அதிக மாசுபாட்டின் போது பாதுகாப்பான வழிகளைப் பின்பற்றியதன் மூலம்.',
    'dashboard.livePollutants': 'நேரடி மாசுபடுத்திகள்',
    'dashboard.historicalTrend': 'வரலாற்று AQI போக்கு',
    'dashboard.aiInsights': 'AI சுகாதார நுண்ணறிவு',
    'dashboard.viewReport': 'விரிவான அறிக்கையைக் காண்க',
    'dashboard.primaryPollutant': 'முதன்மை மாசுபடுத்தி',
    'dashboard.lastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது',

    'precautions.title': 'தினசரி தனிப்பயனாக்கப்பட்ட முன்னெச்சரிக்கைகள்',
    'precautions.subtitle': 'உங்கள் சுகாதார விவரம் மற்றும் இன்றைய காற்றின் தரத்திற்கான தடுப்பு நடவடிக்கைகள்',
    'precautions.outdoor': 'வெளிப்புற செயல்பாட்டு வழிகாட்டல்',
    'precautions.protection': 'பாதுகாப்பு & முகக்கவசம்',
    'precautions.indoor': 'உட்புற காற்று & காற்றோட்டம்',
    'precautions.ayurvedic': 'ஆயுர்வேத & வீட்டு வைத்தியம்',
    'precautions.hydration': 'நீரேற்றம் மற்றும் ஊட்டச்சத்து',
    'precautions.sensitiveAlert': 'உங்கள் ஆரோக்கியத்திற்கான சிறப்பு எச்சரிக்கை',

    'risks.title': 'ஏற்படக்கூடிய நோய்கள் & சுற்றுச்சூழல் அபாய ரேடார்',
    'risks.subtitle': 'தற்போதைய மாசுபாடு மற்றும் வானிலையால் ஏற்படக்கூடிய நோய்கள்',
    'risks.riskScore': 'அபாய மதிப்பெண்',
    'risks.triggers': 'முக்கிய காரணிகள்',
    'risks.watchVideo': 'தாக்க வீடியோவைப் பாருங்கள்',
    'risks.viewDetails': 'நோய் விவரங்களைப் பார்க்கவும்',

    'aqi.good': 'நல்லது (Good)',
    'aqi.moderate': 'மிதமானது (Moderate)',
    'aqi.poor': 'மோசமானது (Poor)',
    'aqi.unhealthySensitive': 'உணர்திறன் கொண்டவர்களுக்கு ஆரோக்கியமற்றது',
    'aqi.unhealthy': 'ஆரோக்கியமற்றது (Unhealthy)',
    'aqi.veryUnhealthy': 'மிகவும் ஆரோக்கியமற்றது (Very Unhealthy)',
    'aqi.hazardous': 'அபாயகரமானது (Hazardous)',

    'video.title': 'எதிர்கால ஆழமான தாக்க வீடியோ பகுப்பாய்வு',
    'video.play': 'வீடியோவை இயக்கு',
    'video.pause': 'நிறுத்து',
    'video.listenAudio': 'ஆடியோவைக் கேளுங்கள்',
    'video.stopAudio': 'ஆடியோவை நிறுத்து',
    'video.narration': 'மருத்துவ ஆடியோ விவரிப்பு',
    'video.progressionTimeline': 'எதிர்கால நோய் முன்னேற்ற காலவரிசை',
    'video.selectStage': 'தாக்கத்தைக் காண நிலையைத் தேர்ந்தெடுக்கவும்',
    'video.organImpairment': 'உறுப்பு சேதம் மற்றும் நோய்க்குறியியல் அளவீடுகள்',
    'video.airwayOcclusion': 'சுவாசப்பாதை அடைப்பு',
    'video.parenchymalFibrosis': 'திசு தடிப்பு',
    'video.systemicStrain': 'உறுப்பு சுமை & அழுத்தம்',
    'video.howToHalt': 'எதிர்கால பாதிப்பை எவ்வாறு தடுப்பது',
    'video.language': 'விவரிப்பு மொழி',

    'common.go': 'செல்',
    'common.refresh': 'புதுப்பி',
    'common.loading': 'ஏற்றுகிறது...',
    'common.close': 'மூடு',
    'common.open': 'திற',
    'common.critical': 'மிக முக்கியமானது',
    'common.high': 'அதிகம்',
    'common.low': 'குறைவு',
  },

  te: {
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.airQualityMap': 'గాలి నాణ్యత మ్యాప్',
    'nav.aiAssistant': 'AI సహాయకుడు',
    'nav.diseases': 'వ్యాధులు',
    'nav.surveillance': 'ఆరోగ్య నిఘా',
    'nav.profile': 'ప్రొఫైల్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.systemActive': 'సిస్టమ్ స్థితి: క్రియాశీలం',

    'topbar.searchPlaceholder': 'ప్రాంతం, వ్యాధి లేదా అంశాలను శోధించండి...',
    'topbar.notifications': 'నోటిఫికేషన్‌లు',
    'topbar.markAllRead': 'అన్నీ చదివినట్లు గుర్తించండి',
    'topbar.dismissAll': 'అన్నీ తీసివేయండి',
    'topbar.noNotifications': 'కొత్త నోటిఫికేషన్‌లు లేవు',
    'topbar.allCaughtUp': 'అన్నీ అప్‌డేట్ చేయబడ్డాయి!',
    'topbar.selectLanguage': 'భాష',

    'dashboard.welcome': 'తిరిగి స్వాగతం',
    'dashboard.subtitle': 'ఇక్కడ మీ రోజువారీ పర్యావరణ ఆరోగ్య వివరాలు ఉన్నాయి.',
    'dashboard.searchCity': 'నగరం పేరు నమోదు చేయండి',
    'dashboard.useMyLocation': 'నా ప్రస్తుత స్థానాన్ని ఉపయోగించు',
    'dashboard.locating': 'స్థానం కోసం వెతుకుతోంది...',
    'dashboard.currentAqi': 'ప్రస్తుత గాలి నాణ్యత (AQI)',
    'dashboard.environmentalImpact': 'పర్యావరణ ప్రభావం',
    'dashboard.hoursAvoided': 'గంటలు కాలుష్య గాలి ప్రభావం నుండి ఈ వారం రక్షించబడ్డాయి.',
    'dashboard.impactNote': 'కాలుష్యం ఎక్కువగా ఉన్న సమయాల్లో సురక్షిత మార్గాలను పాటించడం ద్వారా.',
    'dashboard.livePollutants': 'ప్రస్తుత కాలుష్య కారకాలు',
    'dashboard.historicalTrend': 'చారిత్రక AQI ట్రెండ్',
    'dashboard.aiInsights': 'AI ఆరోగ్య విశ్లేషణ',
    'dashboard.viewReport': 'వివరణాత్మక నివేదికను చూడండి',
    'dashboard.primaryPollutant': 'ప్రధాన కాలుష్య కారకం',
    'dashboard.lastUpdated': 'చివరిగా నవీకరించబడింది',

    'precautions.title': 'రోజువారీ వ్యక్తిగతీకరించిన జాగ్రత్తలు',
    'precautions.subtitle': 'మీ ఆరోగ్య ప్రొఫైల్ మరియు నేటి గాలి నాణ్యత ఆధారంగా నివారణ చర్యలు',
    'precautions.outdoor': 'బయటకు వెళ్లే సమయంలో జాగ్రత్తలు',
    'precautions.protection': 'రక్షణ మరియు మాస్క్ సలహాలు',
    'precautions.indoor': 'ఇంటి లోపలి గాలి & వెంటిలేషన్',
    'precautions.ayurvedic': 'ఆయుర్వేద & ఇంటి నివారణలు',
    'precautions.hydration': 'నీటి వినియోగం & పోషకాహారం',
    'precautions.sensitiveAlert': 'మీ ఆరోగ్యం కోసం ప్రత్యేక హెచ్చరిక',

    'risks.title': 'రాబోయే వ్యాధులు & పర్యావరణ ప్రమాద రాడార్',
    'risks.subtitle': 'ప్రస్తుత కాలుష్య కారకాలు మరియు వాతావరణం వల్ల వచ్చే ప్రమాదాలు',
    'risks.riskScore': 'ప్రమాద స్కోరు',
    'risks.triggers': 'ప్రధాన కారణాలు',
    'risks.watchVideo': 'ప్రభావ వీడియో చూడండి',
    'risks.viewDetails': 'వ్యాధి వివరాలను చూడండి',

    'aqi.good': 'మంచిది (Good)',
    'aqi.moderate': 'మధ్యస్థం (Moderate)',
    'aqi.poor': 'చెడ్డది (Poor)',
    'aqi.unhealthySensitive': 'సున్నితమైన వారికి అనారోగ్యకరం',
    'aqi.unhealthy': 'అనారోగ్యకరం (Unhealthy)',
    'aqi.veryUnhealthy': 'చాలా అనారోగ్యకరం (Very Unhealthy)',
    'aqi.hazardous': 'ప్రమాదకరం (Hazardous)',

    'video.title': 'భవిష్యత్ ప్రభావ వీడియో విశ్లేషణ',
    'video.play': 'వీడియో ప్లే చేయండి',
    'video.pause': 'పాజ్ చేయండి',
    'video.listenAudio': 'ఆడియో వినండి',
    'video.stopAudio': 'ఆడియో ఆపండి',
    'video.narration': 'వైద్య ఆడియో వివరణ',
    'video.progressionTimeline': 'వ్యాధి తీవ్రత కాలక్రమం',
    'video.selectStage': 'ప్రభావాన్ని చూడటానికి దశను ఎంచుకోండి',
    'video.organImpairment': 'అవయవ నష్టం & పాథాలజీ కొలమానాలు',
    'video.airwayOcclusion': 'శ్వాసనాళ అడ్డంకి',
    'video.parenchymalFibrosis': 'ఫైబ్రోసిస్ తీవ్రత',
    'video.systemicStrain': 'అవయవాల భారం & ఒత్తిడి',
    'video.howToHalt': 'భవిష్యత్ నష్టాన్ని ఎలా నివారించాలి',
    'video.language': 'వివరణ భాష',

    'common.go': 'వెళ్ళు',
    'common.refresh': 'రిఫ్రెష్',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.close': 'మూసివేయి',
    'common.open': 'తెరువు',
    'common.critical': 'క్లిష్టమైన',
    'common.high': 'ఎక్కువ',
    'common.low': 'తక్కువ',
  },

  gu: {
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.airQualityMap': 'હવા ગુણવત્તા નકશો',
    'nav.aiAssistant': 'AI સહાયક',
    'nav.diseases': 'રોગો અને બીમારીઓ',
    'nav.surveillance': 'આરોગ્ય દેખરેખ',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.logout': 'લૉગ આઉટ',
    'nav.systemActive': 'સિસ્ટમ સ્થિતિ: સક્રિય',

    'topbar.searchPlaceholder': 'સ્થાન, રોગ અથવા વિષયો શોધો...',
    'topbar.notifications': 'સૂચનાઓ',
    'topbar.markAllRead': 'બધું વાંચેલું ચિહ્નિત કરો',
    'topbar.dismissAll': 'બધું કાઢી નાખો',
    'topbar.noNotifications': 'કોઈ નવી સૂચના નથી',
    'topbar.allCaughtUp': 'બધું અપડેટ છે!',
    'topbar.selectLanguage': 'ભાષા',

    'dashboard.welcome': 'સ્વાગત છે',
    'dashboard.subtitle': 'અહીં તમારું દૈનિક પર્યાવરણીય સ્વાસ્થ્ય વિહંગાવલોકન છે.',
    'dashboard.searchCity': 'શહેરનું નામ દાખલ કરો',
    'dashboard.useMyLocation': 'મારું વર્તમાન સ્થાન વાપરો',
    'dashboard.locating': 'સ્થાન શોધી રહ્યું છે...',
    'dashboard.currentAqi': 'વર્તમાન હવા ગુણવત્તા (AQI)',
    'dashboard.environmentalImpact': 'પર્યાવરણીય પ્રભાવ',
    'dashboard.hoursAvoided': 'કલાક પ્રદૂષિત હવાથી આ અઠવાડિયે બચાવ થયો.',
    'dashboard.impactNote': 'પ્રદૂષણના સમયે સુરક્ષિત રસ્તાઓ અનુસરવાથી.',
    'dashboard.livePollutants': 'લાઈવ પ્રદૂષકો',
    'dashboard.historicalTrend': 'ઐતિહાસિક AQI વલણ',
    'dashboard.aiInsights': 'AI આરોગ્ય સલાહ',
    'dashboard.viewReport': 'વિગતવાર અહેવાલ જુઓ',
    'dashboard.primaryPollutant': 'મુખ્ય પ્રદૂષક',
    'dashboard.lastUpdated': 'છેલ્લે અપડેટ કરેલ',

    'precautions.title': 'દૈનિક વ્યક્તિગત સાવચેતીઓ',
    'precautions.subtitle': 'તમારી સ્વાસ્થ્ય પ્રોફાઇલ અને આજના હવામાન ગુણવત્તા અનુસાર સલાહ',
    'precautions.outdoor': 'બહાર જવાની માર્ગદર્શિકા',
    'precautions.protection': 'સુરક્ષા અને માસ્ક સલાહ',
    'precautions.indoor': 'ઘરની અંદરની હવા અને વેન્ટિલેશન',
    'precautions.ayurvedic': 'આયુર્વેદિક અને ઘરેલું ઉપચાર',
    'precautions.hydration': 'હાઇડ્રેશન અને પોષણ',
    'precautions.sensitiveAlert': 'તમારા સ્વાસ્થ્ય માટે ખાસ ચેતવણી',

    'risks.title': 'સંભવિત રોગો અને પર્યાવરણીય જોખમ રડાર',
    'risks.subtitle': 'હાલના પ્રદૂષણ અને હવામાનને કારણે થતા સંભવિત રોગો',
    'risks.riskScore': 'જોખમ સ્કોર',
    'risks.triggers': 'મુખ્ય કારણો',
    'risks.watchVideo': 'અસર વિડીયો જુઓ',
    'risks.viewDetails': 'રોગ વિગતો જુઓ',

    'aqi.good': 'સારું (Good)',
    'aqi.moderate': 'મધ્યમ (Moderate)',
    'aqi.poor': 'ખરાબ (Poor)',
    'aqi.unhealthySensitive': 'સંવેદનશીલ જૂથો માટે અસ્વસ્થ',
    'aqi.unhealthy': 'અસ્વસ્થ (Unhealthy)',
    'aqi.veryUnhealthy': 'ખૂબ અસ્વસ્થ (Very Unhealthy)',
    'aqi.hazardous': 'જોખમી (Hazardous)',

    'video.title': 'ભવિષ્યની ઊંડી અસરનું વિડીયો વિશ્લેષણ',
    'video.play': 'વિડીયો શરૂ કરો',
    'video.pause': 'અટકાવો',
    'video.listenAudio': 'ઓડિયો સાંભળો',
    'video.stopAudio': 'ઓડિયો બંધ કરો',
    'video.narration': 'ક્લિનિકલ ઓડિયો વર્ણન',
    'video.progressionTimeline': 'રોગ પ્રગતિ સમયરેખા',
    'video.selectStage': 'અસર જોવા માટે તબક્કો પસંદ કરો',
    'video.organImpairment': 'અંગ નુકસાન અને પેથોલોજી મેટ્રિક્સ',
    'video.airwayOcclusion': 'શ્વસનમાર્ગ અવરોધ',
    'video.parenchymalFibrosis': 'ફાઇબ્રોસિસ નુકસાન',
    'video.systemicStrain': 'અંગો પર તણાવ અને બોજ',
    'video.howToHalt': 'ભવિષ્યના નુકસાનને કેવી રીતે અટકાવવું',
    'video.language': 'વર્ણન ભાષા',

    'common.go': 'શોધો',
    'common.refresh': 'તાજું કરો',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.close': 'બંધ કરો',
    'common.open': 'ખોલો',
    'common.critical': 'ગંભીર',
    'common.high': 'વધુ',
    'common.low': 'ઓછું',
  },

  kn: {
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.airQualityMap': 'ವಾಯು ಗುಣಮಟ್ಟ ನಕ್ಷೆ',
    'nav.aiAssistant': 'AI ಸಹಾಯಕ',
    'nav.diseases': 'ರೋಗಗಳು',
    'nav.surveillance': 'ಆರೋಗ್ಯ ಕಣ್ಗಾವಲು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'nav.systemActive': 'ವ್ಯವಸ್ಥೆಯ ಸ್ಥಿತಿ: ಸಕ್ರಿಯ',

    'topbar.searchPlaceholder': 'ಸ್ಥಳ, ರೋಗ ಅಥವಾ ವಿಷಯಗಳನ್ನು ಹುಡುಕಿ...',
    'topbar.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'topbar.markAllRead': 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    'topbar.dismissAll': 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    'topbar.noNotifications': 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    'topbar.allCaughtUp': 'ಎಲ್ಲವೂ ನವೀಕರಿಸಲಾಗಿದೆ!',
    'topbar.selectLanguage': 'ಭಾಷೆ',

    'dashboard.welcome': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'dashboard.subtitle': 'ಇಲ್ಲಿ ನಿಮ್ಮ ದೈನಂದಿನ ಪರಿಸರ ಆರೋಗ್ಯ ಅವಲೋಕನವಿದೆ.',
    'dashboard.searchCity': 'ನಗರದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'dashboard.useMyLocation': 'ನನ್ನ ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ',
    'dashboard.locating': 'ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
    'dashboard.currentAqi': 'ಪ್ರಸ್ತುತ ವಾಯು ಗುಣಮಟ್ಟ (AQI)',
    'dashboard.environmentalImpact': 'ಪರಿಸರ ಪ್ರಭಾವ',
    'dashboard.hoursAvoided': 'ಗಂಟೆಗಳ ಕಾಲ ಮಾಲಿನ್ಯ ಗಾಳಿಯಿಂದ ಈ ವಾರ ರಕ್ಷಣೆ ದೊರೆತಿದೆ.',
    'dashboard.impactNote': 'ಮಾಲಿನ್ಯದ ಸಮಯದಲ್ಲಿ ಸುರಕ್ಷಿತ ಮಾರ್ಗಗಳನ್ನು ಅನುಸರಿಸುವ ಮೂಲಕ.',
    'dashboard.livePollutants': 'ನೇರ ಮಾಲಿನ್ಯಕಾರಕಗಳು',
    'dashboard.historicalTrend': 'ಐತಿಹಾಸಿಕ AQI ಪ್ರವೃತ್ತಿ',
    'dashboard.aiInsights': 'AI ಆರೋಗ್ಯ ಮಾಹಿತಿ',
    'dashboard.viewReport': 'ವಿವರವಾದ ವರದಿಯನ್ನು ವೀಕ್ಷಿಸಿ',
    'dashboard.primaryPollutant': 'ಮುಖ್ಯ ಮಾಲಿನ್ಯಕಾರಕ',
    'dashboard.lastUpdated': 'ಕೊನೆಯ ನವೀಕರಣ',

    'precautions.title': 'ದೈನಂದಿನ ವೈಯಕ್ತಿಕ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು',
    'precautions.subtitle': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಇಂದಿನ ವಾಯು ಗುಣಮಟ್ಟಕ್ಕೆ ತಕ್ಕಂತೆ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು',
    'precautions.outdoor': 'ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆ ಮಾರ್ಗದರ್ಶನ',
    'precautions.protection': 'ರಕ್ಷಣೆ ಮತ್ತು ಮಾಸ್ಕ್ ಸಲಹೆ',
    'precautions.indoor': 'ಒಳಾಂಗಣ ಗಾಳಿ ಮತ್ತು ವಾತಾಯನ',
    'precautions.ayurvedic': 'ಆಯುರ್ವೇದ ಮತ್ತು ಮನೆಮದ್ದುಗಳು',
    'precautions.hydration': 'ನೀರಿನ ಬಳಕೆ ಮತ್ತು ಪೋಷಣೆ',
    'precautions.sensitiveAlert': 'ನಿಮ್ಮ ಆರೋಗ್ಯಕ್ಕಾಗಿ ವಿಶೇಷ ಎಚ್ಚರಿಕೆ',

    'risks.title': 'ಸಂಭಾವ್ಯ ಕಾಯಿಲೆಗಳು ಮತ್ತು ಪರಿಸರ ಅಪಾಯ ರೇಡಾರ್',
    'risks.subtitle': 'ಪ್ರಸ್ತುತ ಮಾಲಿನ್ಯ ಮತ್ತು ಹವಾಮಾನದಿಂದ ಉಂಟಾಗಬಹುದಾದ ರೋಗಗಳು',
    'risks.riskScore': 'ಅಪಾಯ ಸ್ಕೋರ್',
    'risks.triggers': 'ಮುಖ್ಯ ಕಾರಣಗಳು',
    'risks.watchVideo': 'ಪ್ರಭಾವದ ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ',
    'risks.viewDetails': 'ರೋಗದ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',

    'aqi.good': 'ಉತ್ತಮ (Good)',
    'aqi.moderate': 'ಮಧ್ಯಮ (Moderate)',
    'aqi.poor': 'ಕಳಪೆ (Poor)',
    'aqi.unhealthySensitive': 'ಸೂಕ್ಷ್ಮ ಜನರಿಗೆ ಅನಾರೋಗ್ಯಕರ',
    'aqi.unhealthy': 'ಅನಾರೋಗ್ಯಕರ (Unhealthy)',
    'aqi.veryUnhealthy': 'ಬಹಳ ಅನಾರೋಗ್ಯಕರ (Very Unhealthy)',
    'aqi.hazardous': 'ಅಪಾಯಕಾರಿ (Hazardous)',

    'video.title': 'ಭವಿಷ್ಯದ ಆಳವಾದ ಪರಿಣಾಮದ ವೀಡಿಯೊ ವಿಶ್ಲೇಷಣೆ',
    'video.play': 'ವೀಡಿಯೊ ಪ್ಲೇ ಮಾಡಿ',
    'video.pause': 'ವಿರಾಮಗೊಳಿಸಿ',
    'video.listenAudio': 'ಆಡಿಯೊ ಆಲಿಸಿ',
    'video.stopAudio': 'ಆಡಿಯೊ ನಿಲ್ಲಿಸಿ',
    'video.narration': 'ವೈದ್ಯಕೀಯ ಆಡಿಯೊ ನಿರೂಪಣೆ',
    'video.progressionTimeline': 'ರೋಗದ ಮುನ್ನಡೆಯ ಕಾಲಾವಧಿ',
    'video.selectStage': 'ಪರಿಣಾಮವನ್ನು ನೋಡಲು ಹಂತವನ್ನು ಆರಿಸಿ',
    'video.organImpairment': 'ಅಂಗ ಹಾನಿ ಮತ್ತು ರೋಗಶಾಸ್ತ್ರದ ಮೆಟ್ರಿಕ್ಸ್',
    'video.airwayOcclusion': 'ಉಸಿರಾಟದ ನಾಳದ ತಡೆ',
    'video.parenchymalFibrosis': 'ಫೈಬ್ರೋಸಿಸ್ ಹಾನಿ',
    'video.systemicStrain': 'ಅಂಗಗಳ ಮೇಲಿನ ಒತ್ತಡ',
    'video.howToHalt': 'ಭವಿಷ್ಯದ ಹಾನಿಯನ್ನು ತಡೆಯುವುದು ಹೇಗೆ',
    'video.language': 'ನಿರೂಪಣೆ ಭಾಷೆ',

    'common.go': 'ಹೋಗಿ',
    'common.refresh': 'ತಾಜಾಗೊಳಿಸಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.open': 'ತೆರೆಯಿರಿ',
    'common.critical': 'ಗಂಭೀರ',
    'common.high': 'ಹೆಚ್ಚು',
    'common.low': 'ಕಡಿಮೆ',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('vayu_language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setLanguageState(langCode);
      try {
        localStorage.setItem('vayu_language', langCode);
      } catch (e) {
        console.error('Failed to save language preference:', e);
      }
    }
  };

  const t = useMemo(() => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    const fallbackDict = TRANSLATIONS.en;

    return (key, fallback) => {
      return currentDict[key] || fallbackDict[key] || fallback || key;
    };
  }, [language]);

  const currentLanguageMeta = useMemo(() => {
    return LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languagesList: LANGUAGES,
        currentLanguageMeta,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
